version: "3.9"
services:

  mysql:
    image: "mysql:latest"
    container_name: todo_mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rockmyroot
      MYSQL_DATABASE: todo_list
      MYSQL_USER: todouser
      MYSQL_PASSWORD: todopass
    volumes:
      - E:\Workspace\java\todo-spring-boot\data\mysql:/var/lib/mysql
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: todo_phpmyadmin
    ports:
      - 8888:80
    links:
      - mysql:db

