server:
  port: 8080
  servlet:
    contextPath: /api
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/todo_list?createDatabaseIfNotExist=true
    username: todouser
    password: todopass
    initialization-mode: always

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

  liquibase:
    enabled: false

app:
  jwt:
    secret: SuperSecretKeygen
    expiration_time: 864000000
    token_prefix: "Bearer "
    header: Authorization
    sign_up_url: "/sign-up"