server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/todo_list?createDatabaseIfNotExist=true
    username: todouser
    password: todopass
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

  liquibase:
    enabled: false